---
 - name: Install ruby & required packages
   apt:
     name: "{{ item }}"
     state: present
     update_cache: yes
   with_items:
     - ruby-full
     - ruby-bundler
     - build-essential
   tags: ruby
